apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260613-210229-n6a4xsq9964s-service
spec:
  selector:
    app: enterprise-system-20260613-210229-n6a4xsq9964s
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
